### ISSUE TITLE
Convert module to SilverStripe coding guidelines

### ISSUE THREAD

**Issue by spekulatius** [deviateltd/silverstripe-googlesitemapautoupdate#2]
The modules should align with the code style guide of SilverStripe (https://docs.silverstripe.org/en/3.1/getting_started/coding_conventions/). I've seen some places where the code style wasn't followed proper. I'm happy to submit some pull requests to help out here.

Another idea would be to set up a Jenkin/Sonar with https://github.com/spekulatius/silverstripe-codesniffer ...

**Comment by phptek** [comment]
@spekulatius thanks. I'm totally on board with these guidelines, however I'm confused: silverstripe-framework contains a `.editorconfig` file, which I've stipulates SS guidelines in the EditorConfig ini file format. If I apply that to the module, I get totally different results than you (several newline changes as well as indentation changes).

I'm using phpStorm 9.0.2 with the EditorConfig plugin enabled, with silverstripeframework/.editorconfig

**Comment by spekulatius** [comment]
Hello @phptek ,

I'm using sublime and orientate myself on the coding conventions. Maybe you could give me an example where the code style seems to not match? Then we could investigate which is matching with the conventions. 

Spek

**Comment by phptek** [comment]
@spekulatius I have pushed changes to master, which includes a lightly modified `.editorconfig` file, sourced from `silverstripe-framework`, then  tagged `1.0.1`.

As you can see, the diff shows changes to every line in the file. While I haven't run `file` or `hexedit` over it to see the _actual_ changes, I assume that either myself or my colleagues have different IDE CR/LF and tab/indent settings (something which I'm already changing in-house).

I pushed the changes  and tagged as they were non-breaking. Please feel free to comment if you can see any  problems in the approach.

Thanks for your interest :-)

**Comment by spekulatius** [comment]
No problem @phptek :)
